name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.3'
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install ffmpeg
      run: |
        sudo apt install ffmpeg
    - name: Install dependencies
      run: |
        gem install bundler --no-document
        bundle install
    - name: Run test
      run: bundle exec rake
